baseURL = 'https://fivetwentythree.github.io/hblog/'
languageCode = 'en-us'
title = "Your Blog's Title"
theme = 'ritzy'

# Enable Hugo's built-in syntax highlighting.
# This is far more performant than a JavaScript library.
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "monokai"
    noClasses = false

[params]
  author = "Your Name"
  description = "Your personal blog description."